name: 'SAST Check'
description: 'Run SAST checks in your code'
steps:
  - name: DataDog API secret
    with:
      DD_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
    env:
      DD_CLIENT_API_KEY: ${{ secrets.DD_CLIENT_API_KEY }}
inputs:
  path: 
    description: 'Path to run SAST checks on'
    required: false
    default: '.'
outputs:
    result: 
        description: 'Output of SAST checks'
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
    - ${{ inputs.path }}
