name: 'SAST Check'
description: 'Run SAST checks in your code'
inputs:
  path: 
    description: 'Path to run SAST checks on'
    required: false
    default: '.'
outputs:
    result: 
        description: 'Output of SAST checks'
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
    - ${{ inputs.path }}
env:
  DD_CLIENT_API_KEY: 2c9e77e2533c77e056567909a6fac4f7
